version: '3'

services:
  api:
    container_name: wongames_api
    image: arthur11/won-games-api:latest
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USERNAME: wongames
      DATABASE_PASSWORD: wongames123
      DATABASE_NAME: wongames
      STRIPE_KEY: 'pk_test_51NrldvBCLqj6zcs196GiYFAxrI8Vy7yTowvOobOeqKTsQZ3lQmFXtfRNNXdGt6B6VKcFLWnuatErWQnDLu22WIFB005ocvFhiA'
    ports:
      - '1337:1337'
    depends_on:
      - db

  db:
    container_name: wongames_db
    image: arthur11/won-games-database:latest
    ports:
      - '5432:5432'